spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka
#    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

server:
  port: 9000
