spring:
  application:
    name: zuul
  redis:
    database: 0
    host: 47.100.249.163
    port: 6379
    password: wework2018
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

zuul:
################# 瞬时并发大小 #################
  semaphore:
    max-semaphores: 1000

################# 路由 #################
  ignored-services: '*'
  routes.CONSUMER: /consumer/**

################# 敏感header隔离 #################
  #sensitive-headers: Cookie,Set-Cookie,Authorization
  #security登入后重定向请求栏回到网关地址而不是实例地址
  #add-host-header: true

################# 限流 #################
ratelimit:
  type: URI
#  model: "{'consumer':{'count':1,'time':1}}"
  uri: "{'/consumer/test':{'count':1,'time':1}}"

################# 超时配置 #################
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 6000
  MaxAutoRetriesNextServer: 0

##################rocketmq#######################
# 消费者的组名
apache:
  rocketmq:
    consumer:
      PushConsumer: victor_test
      producerGroup: victor_test_Producer
      instacneName: victor_test_Consumer
    namesrvAddr: 47.100.249.163:9876
    producer:
      instacneName: victor_test_Producer
    topic: VictorTest
    tag: VictorTest
##################rocketmq#######################

