spring:
  application:
    name: provider

eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30



server:
  port: 9010