server:
  port: 8761
eureka:
  instance:
    hostname: peer02
  server:
    use-read-only-response-cache: false
    enable-self-preservation: false
    peer-eureka-nodes-update-interval-ms: 60000
  client:
    service-url:
      defaultZone: http://peer01:8760/eureka